#define BEAR_ "texture\\items\\bear.png"
#define CANDY_ "texture\\items\\candy.png"
#define FOOD_ "texture\\items\\food.png"
#define FOOD2_ "texture\\items\\food2.png"
#define FOOTBALL_ "texture\\items\\football.png"
#define HAPPYP_ "texture\\items\\happy.png"
#define HAPPYD_ "texture\\items\\sad.png"
#define HPP_ "texture\\items\\hpUp.png"
#define HPD_ "texture\\items\\hpDown.png"
#define MILK_ "texture\\items\\milk.png"
#define MONEY_ "texture\\items\\money.png"
#define PAINTER_ "texture\\items\\painter.png"
#define TEACHER_ "texture\\items\\teacher.png"
#define WRENCH_ "texture\\items\\wrench.png"

#define BEAR_ID 0
#define CANDY_ID 1
#define FOOD_ID 2
#define FOOD2_ID 3
#define FOOTBALL_ID 4
#define MILK_ID 5
#define MONEY_ID 6
#define PAINTER_ID 7
#define TEACHER_ID 8
#define WRENCH_ID 9